/* ── Export module ─────────────────────────────────────────────
   Generates a Markdown file from the current IA and triggers
   a browser download.
   Exposes: window.Export.download()
   ─────────────────────────────────────────────────────────── */
(function () {
  'use strict';

  /* ── Build Markdown string ───────────────────────────────── */
  function buildMarkdown() {
    var state = State.getState();
    var lines = [];

    lines.push('# Information Architecture');
    lines.push('');
    lines.push('*Generated by IA Helper*');
    lines.push('');
    lines.push('---');
    lines.push('');

    /* Architecture Map tree */
    lines.push('## Site Structure');
    lines.push('');

    if (state.rootIds.length === 0) {
      lines.push('*(No pages mapped yet)*');
    } else {
      state.rootIds.forEach(function (id) {
        writeNode(id, 0, lines, state);
      });
    }

    lines.push('');

    /* Feature 8: Utility Menu section */
    if (state.utilityEnabled && state.utilityIds.length > 0) {
      lines.push('---');
      lines.push('');
      lines.push('## Utility Menu');
      lines.push('');
      state.utilityIds.forEach(function (id) {
        writeNode(id, 0, lines, state);
      });
      lines.push('');
    }

    lines.push('---');
    lines.push('');

    /* Element Box */
    lines.push('## Element Box');
    lines.push('');
    if (state.ebIds.length === 0) {
      lines.push('*(Empty)*');
    } else {
      state.ebIds.forEach(function (id) {
        var card = state.cards[id];
        if (!card) return;
        lines.push('- ' + card.title + (card.description ? ' — ' + card.description : ''));
      });
    }

    lines.push('');
    return lines.join('\n');
  }

  function writeNode(id, depth, lines, state) {
    var card = state.cards[id];
    if (!card) return;

    var indent = repeat('  ', depth);
    var desc   = card.description ? ' — ' + card.description : '';
    lines.push(indent + '- **' + card.title + '**' + desc);

    /* Nested elements */
    card.nestedIds.forEach(function (nid) {
      var nc = state.cards[nid];
      if (!nc) return;
      var ndesc = nc.description ? ' — ' + nc.description : '';
      lines.push(indent + '  - ' + nc.title + ndesc + ' *(element)*');
    });

    /* Child pages */
    card.childIds.forEach(function (cid) {
      writeNode(cid, depth + 1, lines, state);
    });
  }

  function repeat(str, n) {
    var result = '';
    for (var i = 0; i < n; i++) result += str;
    return result;
  }

  /* ── Trigger download ────────────────────────────────────── */
  function download() {
    var md   = buildMarkdown();
    var blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
    var url  = URL.createObjectURL(blob);
    var a    = document.createElement('a');
    a.href     = url;
    a.download = 'ia-export.md';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  window.Export = { download: download };
})();
